# Generated by Django 3.0.4 on 2020-03-23 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='car',
            field=models.CharField(max_length=255, verbose_name='Автмобиль'),
        ),
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.CharField(max_length=255, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='order',
            name='year',
            field=models.CharField(blank=True, max_length=4, verbose_name='Год выпуска'),
        ),
    ]
