# Generated by Django 3.0.4 on 2020-03-23 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesettings',
            name='address',
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='text_bottom',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
