# Generated by Django 3.0.4 on 2020-03-23 21:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0001_squashed_0021'),
        ('core', '0002_auto_20200323_2148'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sitesettings',
            old_name='logo',
            new_name='logo_bottom',
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='logo_top',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
    ]
