# Generated by Django 3.0.5 on 2020-04-01 21:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0001_squashed_0021'),
        ('core', '0003_auto_20200324_0045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='logo_bottom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='Логотип - низ'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='logo_top',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='Логотип - верх'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='phone',
            field=models.CharField(blank=True, max_length=255, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='slogan_bottom',
            field=models.CharField(blank=True, max_length=255, verbose_name='Слоган - низ'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='slogan_top',
            field=models.CharField(blank=True, max_length=255, verbose_name='Слоган - верх'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='text_bottom',
            field=models.CharField(blank=True, max_length=255, verbose_name='Текст - низ'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='work_time',
            field=models.CharField(blank=True, max_length=255, verbose_name='Время работы'),
        ),
    ]
