# Generated by Django 3.0.4 on 2020-03-23 21:28

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0045_assign_unlock_grouppagepermission'),
        ('home', '0004_auto_20200323_2148'),
    ]

    operations = [
        migrations.CreateModel(
            name='InnerPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('body', wagtail.core.fields.StreamField([('text', wagtail.core.blocks.RichTextBlock())], blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='body',
            field=wagtail.core.fields.StreamField([('main', wagtail.core.blocks.StructBlock([('header1', wagtail.core.blocks.CharBlock(label='Первая линия заголовка')), ('header2', wagtail.core.blocks.CharBlock(label='Вторая линия заголовка')), ('header3', wagtail.core.blocks.CharBlock(label='Третья линия заголовка')), ('items', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(required=True)), ('text', wagtail.core.blocks.CharBlock(max_length=255, required=True))]), label='Список'))])), ('features', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock()), ('features', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(max_length=100, required=True)), ('image', wagtail.images.blocks.ImageChooserBlock(required=True)), ('text', wagtail.core.blocks.CharBlock(max_length=255, required=True))])))])), ('action', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(label='Заголовок')), ('text', wagtail.core.blocks.RichTextBlock(label='Содержимое')), ('button_text', wagtail.core.blocks.CharBlock(label='Текст кнопки'))])), ('cars', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock()), ('cars', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(help_text='Например: Nissian Teana', label='Название автомобиля', max_length=100, required=True)), ('year', wagtail.core.blocks.CharBlock(help_text='Например: 2008', label='Год выпуска', max_length=100, required=True)), ('engine', wagtail.core.blocks.CharBlock(help_text='Объем в литрах, например: 1.5', label='Объем двигателя', required=True)), ('gear', wagtail.core.blocks.ChoiceBlock(choices=[('МКПП', 'МКПП'), ('АКПП', 'АКПП'), ('Вариатор', 'Вариатор')], help_text='Вид трансмиссии', label='Трансмиссия')), ('price', wagtail.core.blocks.CharBlock(help_text='Цена в рублях с пробелами', label='Цена', max_length=255, required=True)), ('image', wagtail.images.blocks.ImageChooserBlock(help_text='Изображение автомобиля', label='Фотография', required=True)), ('logo', wagtail.images.blocks.ImageChooserBlock(help_text='Логотип производителя', label='Логотип', required=True))])))])), ('steps', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock()), ('steps', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('number', wagtail.core.blocks.CharBlock(max_length=2, required=True)), ('title', wagtail.core.blocks.CharBlock(max_length=100, required=True)), ('text', wagtail.core.blocks.CharBlock(max_length=255, required=True))])))])), ('form', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock())])), ('map', wagtail.core.blocks.StructBlock([('yandex_map', wagtail.core.blocks.TextBlock(help_text='Код из конструктора Яндекс карт')), ('text', wagtail.core.blocks.RichTextBlock()), ('show_phone', wagtail.core.blocks.BooleanBlock(required=False)), ('show_work_time', wagtail.core.blocks.BooleanBlock(required=False))]))], blank=True, null=True),
        ),
    ]
